/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HebergementsRouteImport } from './routes/hebergements'
import { Route as ActivitesRouteImport } from './routes/activites'
import { Route as IndexRouteImport } from './routes/index'

const HebergementsRoute = HebergementsRouteImport.update({
  id: '/hebergements',
  path: '/hebergements',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitesRoute = ActivitesRouteImport.update({
  id: '/activites',
  path: '/activites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activites': typeof ActivitesRoute
  '/hebergements': typeof HebergementsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activites': typeof ActivitesRoute
  '/hebergements': typeof HebergementsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activites': typeof ActivitesRoute
  '/hebergements': typeof HebergementsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/activites' | '/hebergements'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/activites' | '/hebergements'
  id: '__root__' | '/' | '/activites' | '/hebergements'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitesRoute: typeof ActivitesRoute
  HebergementsRoute: typeof HebergementsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/hebergements': {
      id: '/hebergements'
      path: '/hebergements'
      fullPath: '/hebergements'
      preLoaderRoute: typeof HebergementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activites': {
      id: '/activites'
      path: '/activites'
      fullPath: '/activites'
      preLoaderRoute: typeof ActivitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitesRoute: ActivitesRoute,
  HebergementsRoute: HebergementsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
